Feature/login
JonathanACO/AIMSApp pull request #1
Opened 2024-08-19 16:17 UTC by XAEA2112

2024-08-20 01:16 UTC, Wilovy09 commented
El diseño, ya que tenemos el diseño hecho en figma de la aplicación y al parecer esta parte del login ya no va estar cambiando. Creo que ya puedes darle estilos acordes al figma (creo que si tienes acceso).

![image](https://github.com/user-attachments/assets/7a6a6650-d39f-42ff-82c1-ca2893b6c144)

Obviamente omite las partes de branding, dejango el hueco para poder poner cualquier logo.

2024-08-20 01:20 UTC, Wilovy09 commented
Esto no te corresponde al 100%, pero estaria bien que hicieras que el fondo se viera blanco por defecto con el theme de ionic https://ionicframework.com/docs/theming/basics

![image](https://github.com/user-attachments/assets/aba963df-d8be-4a78-8d1d-2c98a52ab1b9)

Tambien recuerda que no debemos de tener la función de registrar ya que el enfermero no tendra acceso a poder crear más enfermeros. De esto se va encargar el panel de administrador para crear o eliminar enfermeros, aqui solo tendremos:
- Login
- Logout
Y si acaso, Home

2024-08-20 01:22 UTC, Wilovy09 commented on backend/app/controllers/auth_controller.ts
> +  }
Esta función de register no la necesitamos, porque en esta APP no debemos de poder registrar nuevos enfermeros.

2024-08-20 02:12 UTC, Wilovy09 requested changes
Tambien necesitas darle una checada a porque no te esta formateando con el `prettier` no si sea porque no tienes la extensión instalada en VSCode o porque no tienes el `formatOnSave` pero si es necesario que le des una formateada a todos estos archivos en los que estuviste trabajando porque si esta un poco raro la forma en la que esta ahorita algunas llaves.

2024-08-20 02:12 UTC, Wilovy09 commented on frontend/src/router/routes.ts
> +  },
Todo este objeto de `/register` se debe borrar por lo que ya te comente

2024-08-20 02:12 UTC, Wilovy09 commented on frontend/src/stores/auth.ts
> +        const result = await api('POST', '/login', payload)
Estas request a la API las podemos separar en un repositorio. Todo lo que sea manejo con base de datos debe ir en un repositorio.

Entonces quedaria algo asi

```ts
// src/repositories/authRepository.ts
import { api } from "@/helpers/apiBackend";

export class AuthRepository {
  public async login() {
    return await api("POST", "/login", payload: {
      email: string
      password: string    
    });
  }
  // tus demas requests...
}
```
Y al momento de llamarlo en este archivo hariamos esto:
```ts
import { AuthRepository } from "@/repositories/authRepository";

const authRepository = new AuthRepository();

// y cuando lo vayamos a usar tendriamos que acceder a sus metodos
const result = await authRepository.login(payload)
```

2024-08-20 17:51 UTC, XAEA2112 commented on frontend/src/entities/user.ts
> +}
Te acuerdas que en el código de la página home me daba error al querer usar el email para mostrar "Welcome, {{user.email}}? Me recomendaste que lo separara definiendo las entidades de user en un archivo aparte, y después de eso ya se desplegaba bien la página no sé si eso fue lo que solucionó el error pero después de eso ya no había que recargar la página para que mostrara el contenido

2024-08-21 14:44 UTC, JonathanACO requested changes

2024-08-21 14:44 UTC, JonathanACO commented on frontend/src/pages/Login/LoginPage.vue
> +const errorMessage = ref('');
No estas usando esta variable

2024-08-21 14:44 UTC, JonathanACO commented on frontend/src/pages/Login/LoginPage.vue
> +const passwordError = ref(false);
Para las variables que sean booleanas usa nombres que sean más como pregunta de si o no agregando al principio un "is", "has" o "are", en este caso creo que esta mejor el nombre `hasEmailError` y `hasPasswordError`

2024-08-21 14:44 UTC, JonathanACO commented on frontend/src/pages/Login/LoginPage.vue
> +const isLoading = ref(false);
Junta las variables booleanas al final de la declaración de variables, y también tienes que usar esta variable para implementar un loader, busca algún loader y hazlo como componente global y que cada quien le pueda dar el tamaño que quiera

2024-08-21 14:44 UTC, JonathanACO commented on frontend/src/pages/Login/LoginPage.vue
> +import azulImage from "@/assets/images/Azul.png"
Elimina el import y borra las imágenes del archivo assets ya que no vamos a usar estos logos

2024-08-21 14:44 UTC, JonathanACO commented on frontend/src/pages/Home/HomePage.vue
Esta muy bien que hagas este tipo de cosas para aprender y practicar pero al ser cosas que no van a ser utilizadas en la aplicación lo mejor es que al hacer PR lo dejes vacío

2024-08-21 14:44 UTC, JonathanACO commented on frontend/src/layouts/MainLayout.vue
> +      <RouterLink to="/login">Login</RouterLink>
Lo mismo que el comentario anterior

2024-09-06 17:04 UTC, lcasass3 requested changes

2024-09-06 17:04 UTC, lcasass3 commented on frontend/src/repositories/authRepository.ts
> +  public async login(payload: any) {
y tambien en la store, para que el compilador marque error si se quiere usar ell método con parámetros inválidos

2024-09-06 17:04 UTC, lcasass3 commented on frontend/src/repositories/authRepository.ts
Haz los métodos estáticos, para que no tengas que crear una instancia de la clase cada que necesitas el repositorio.

2024-09-06 17:04 UTC, lcasass3 commented on frontend/src/repositories/authRepository.ts
https://www.typescriptlang.org/docs/handbook/2/classes.html#static-members

2024-09-06 18:08 UTC, lcasass3 requested changes
Otra cosa, necesito que elimines el directorio de `frontend` porfa, es decir, vas a sacar todo lo que está en `frontend` a raíz, y la carpeta de frontend se va a eliminar.
Solo ten cuidado ya que te va a aparecer que modificaste todos los archivos, haz este cambio en un commit separado. O sea commitea todo lo que hayas modificado antes, y después haz un solo commit con el movimiento de directorio.

2024-09-06 18:08 UTC, lcasass3 commented on frontend/src/stores/auth.ts
> +  const staff = ref(null);
Tipa esto ya que no solamente puede ser `null`, también puede ser de tipo `Staff` me parece

2024-09-06 18:08 UTC, lcasass3 commented on frontend/src/stores/auth.ts
> +  const staff = ref(null);
Por cierto, cambia la entidad de Staff a Nurse de una vez

2024-09-06 18:08 UTC, lcasass3 commented on frontend/src/stores/auth.ts
> +  function authenticate(result: any) {
Busca un mejor `type` para esto

2024-09-06 18:08 UTC, lcasass3 commented on frontend/src/stores/auth.ts
> +  async function login(payload: any) {
Tipa esto como te mencioné en el `repository`

2024-09-06 18:08 UTC, lcasass3 commented on frontend/src/theme/styles.css
> +}
Aquí en lugar de crear las clases y luego utilizarlas mezcladas con tailwind, te recomiendo mejor crear componentes ya que hace el código más claro y reutilizable. Por ejemplo puedes crear un component de `VCard` y uno de `VButton`.

2024-09-13 17:12 UTC, lcasass3 requested changes

2024-09-13 17:12 UTC, lcasass3 commented on src/helpers/authErrorsHandler.ts
Aquí hay algo muy importante y es reconocer los _casos de uso_ y el _control_ que podemos tener sobre los errores en la aplicación. El handler está bien, me gusta que literalmente aborda cualquier caso de error que pueda surgir en una petición, pero esto es útil cuando consumimos una api sobre la cual no tenemos inferencia, no la podemos modificar, en este caso **SI podemos modificar nuestro backend para hacer los errores más simples.**
En la rama de backend te voy a comentar que es lo que necesitas hacer allá, pero básicamente es solo manejar la respuesta directamente. Si tu mandas un mensaje de respuesta personalizado en caso de error desde backend, aquí puedes solamente hacer lo siguiente:
```
export function handleErrors(error: unknown) {
  // Revisar si el error es una instacia de AxiosError, es decir, es un error proveniente de la llamada http
  if (error instanceof AxiosError) {
    // Si el error tiene una respuesta, y esa respuesta tiene data que es de tipo string (un mensaje), podemos mostrarlo 
    // directamente como viene.
    if (error.response && typeof error.response.data === "string") {
      showErrorToast(error.response.data);
    } else {
      // En caso de que o no haya response, o la data sea de otro tipo mostramos un error desconocido
      showErrorToast("Ocurrió un error inesperado");
    }
  // En caso de que el error no sea una instancia de Axios, mostramos un error desconocido.
  } else {
    showErrorToast("Ocurrió un error inesperado");
  }
}
```
Si ves, cuando nosotros manejamos mejor los errores desde el backend también reducimos significativamente la complejidad necesaria para manejarlos en frontend, pasamos de _30+ lineas y un archivo de mapa de mensajes_ adicional a _15 lineas y ningún file extra_. Considera esto siempre que tengas acción sobre el backend que consume tu proyecto.

2024-09-13 17:12 UTC, lcasass3 commented on src/helpers/errorMessagesMap.ts
Ya no necesitarás esto

2024-09-24 17:03 UTC, lcasass3 approved these changes
Ya son solo estos detalles, solo revisalos muy bien porfa y asegurate de corregirlos correctamente. Igual cualquier cosa me dices y ya te doy approve para que terminando puedas dar merge

2024-09-24 17:03 UTC, lcasass3 commented on src/stores/useAuthStore.ts
> +    const token = await AuthRepository.login(credentials);
Revisa los cambios de tipado que pueden surgir por lo que te comenté ahorita, porque realmente `login` desde backend no retorna solo un `token` en forma de string, sino un objeto completo de `accessToken` o algo similar

2024-09-30 21:55 UTC, merged