Feature/vista detalle de paciente
JonathanACO/AIMSApp pull request #2
Opened 2024-08-22 04:38 UTC by Wilovy09

![image](https://github.com/user-attachments/assets/8dc95630-aa1d-4498-abaa-d7658cacefc4)

Los `margins` se agregaran al layout y no a la vista.

Los botones, `1`, `2` y `3` quedan pendientes hasta saber que funciones son las que se requieren especificamente.

NO DARLE MERGE hasta que la vista tenga esos 3 botones.

2024-08-26 15:59 UTC, JonathanACO requested changes

2024-08-26 15:59 UTC, JonathanACO commented on frontend/src/pages/DetallesPaciente/DetallesPacientePage.vue
> +      </div>
Agregar un scroll en "y" por si hay demasiadas consultas

2024-08-26 15:59 UTC, JonathanACO commented on frontend/src/pages/DetallesPaciente/DetallesPacientePage.vue
> +            </button>
Agregar una animación similar a los botones de ionic en hover y active

2024-08-26 21:04 UTC, JonathanACO requested changes

2024-08-26 21:04 UTC, JonathanACO commented on frontend/src/router/routes.ts
> +        name: "detalles-paciente",
Pon el nombre de las rutas en ingles

2024-09-18 19:43 UTC, lcasass3 requested changes

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
Recuerda nombrar las páginas en inglés, `PatientDetailsPage.vue`

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +const patientId: number = Number(route.params.id);
No es necesario tipar explícitamente si ya tenemos el constructor a lado.

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +const patientDetails = ref<Patient[] | null>(null);
Con respecto al cambio que te dije en backend, este tipo va a cambiar a `Patient`

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +const patientDetails = ref<Patient[] | null>(null);
Además, nombra el ref como `patient` nada más, no es necesario el details

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +const appointmentsHistory = ref<Appointment[] | null>(null);
Igual se me hace mejor `appointments`

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +const formattedPatientId: string = generateId(patientId.toString());
`formattedNurseId` o `patientIdentifier` o algo que se te ocurra más acorde

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +const roomDetails = ref<Room[] | null>(null);
`room`

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +    patientDetails.value = await patientRepository.getDetails(patientId ?? 0);
Valida que exista un `patientId` en lugar de pasarle 0, en caso de que no lo haya lanza error

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +    console.error(e);
Maneja los errores con `swal`, no solo `console.logs`

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +      await appointmentsRepository.getAppointmentsHistory(Number(patientId));
Es necesario volver a llamar el constructor `Number` si ya es un número??

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +    console.error(e);
Maneja errores

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +    }
Cuando el retorno del endpoint sea `Patient` ya no tienes que hacer este `find` ni el `if()` me parece

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +    console.error(e);
Maneja errores

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +  await getRoomDetails();
Puedes renombrar algunos métodos, `getPatient`, `getRoom`

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +          v-for="patientDetails in patientDetails"
Recuerda que los `v-for` deben tener una `:key` obligatoriamente

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +          <span v-for="room in roomDetails">
`:key`

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +            <p>{{ appointmentsHistory?.length }}</p>
Necesitas mostrar algo en caso de que sea `null`

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +    <IonContent class="ion-padding" :fullscreen="true">
En general acuerdate de manejar los casos en que no haya `appointments`, no haya `patient` o `room`, pq actualmente solo crashea. Muestra textos indicando que no hay registros, usa conditional rendering, etc.

2024-09-18 19:43 UTC, lcasass3 commented on src/pages/DetallesPaciente/DetallesPacientePage.vue
> +          v-if="appointmentsHistory"
Recuerda revisar que no sea `null` y además que el arreglo no esté vacío

2024-09-18 19:43 UTC, lcasass3 commented on src/repositories/AppointmentsRepository.ts
Algo que le había comentado a Miguel es que agregue el retorno explícitamente de los métodos en el repositorio en base a lo que está en backend, como el retorno en realidad es `any`, puedes tipar directamente el retorno del método.

2024-09-18 19:43 UTC, lcasass3 commented on src/repositories/AppointmentsRepository.ts
También, `axios` te va a retornar un objeto `data`, saca solo la propiedad que necesites de ese objeto y retornala. Revisa igual la rama de Miguel, ya corrigió esta parte en sus repos

2024-09-18 19:43 UTC, lcasass3 commented on src/utilities/dateFormat.ts
Renombra la carpeta a `utils`

2024-09-18 19:43 UTC, lcasass3 commented on src/utilities/dateFormat.ts
> +export function dateFormat(date: Date) {
Me parece bien que hagas el formateo de fechas nativo para no depender de librerías por la cuestión del internet, solo sé más específico con el nombre de las funciones ya que puede haber más de un tipo de formato que se utilice

2024-09-18 19:43 UTC, lcasass3 commented on src/utilities/getDaysDifference.ts
> +  return `${dayDifference} dias`;
No retornes la `string`, retorna solamente el resultado que es la diferencia.

2024-09-19 18:55 UTC, Wilovy09 commented on src/assets/fonts/Inter_18pt-Black.ttf
No pero mira, en una chequeada asi a ojo,

CSS descargado:
![image](https://github.com/user-attachments/assets/ba251b18-8d0b-4588-9196-51029f60ead8)

Creo que es el archivo de:
![image](https://github.com/user-attachments/assets/63fefea4-911b-4f05-8ecf-e90ff8ad2179)
Y solo pesa 1.42kb, entonces no lo veo con problema de bundlesize o asi, pero como tu veas

---

Lo que me preocupa es que tenemos 3.15MB/3.17MB de descarga, tarda de 5s a 8s en descargar todo. es demasiado lo más que habia escuchado eran 6MB pero no recuerdo si era en la web de Vercel/Next estamos a la mitad de ellos y no hacemos ni la mitad de ellos, lol, hay que buscar como optimizar esto o reducir nuestras dependencias, el problema es que es Ionic y Ionic necesita demasiadas cosas (por eso ya no se usa y se usan tecnos nativas como react-native o flutter) por ser webview
![image](https://github.com/user-attachments/assets/2efe55df-0be9-4718-9df7-721bd7447e35)

2024-09-19 18:56 UTC, Wilovy09 commented on src/assets/fonts/Inter_18pt-Black.ttf
@lcasass3

2024-09-21 03:07 UTC, Wilovy09 commented on src/helpers/formatPatientId.ts
no habiamos quedado en que PXXX era para el paciente y PFXXX para el enfermero?

2024-10-18 07:16 UTC, merged